# Generated by Django 4.0.6 on 2022-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Brinquedo', 'Brinquedo'), ('Roupa', 'Roupa'), ('Sapato', 'Sapato'), ('Camisa', 'Camisa'), ('Esportes', 'Esporte'), ('Eletronico', 'Eletronico')], max_length=12, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
