# Generated by Django 4.0.6 on 2022-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default=1, max_length=50, verbose_name='Descricao'),
            preserve_default=False,
        ),
    ]
